Tests
peeredu/task_002 pull request #1
Opened 2024-02-27 19:21 UTC by zv0r

Проверь, пожалуйста, эту херь повнимательнее

2024-02-27 20:25 UTC, fortune76 commented on tests/test_pascal_matrix.py
> +import os.path
зачем отдельно его?

2024-02-27 20:26 UTC, fortune76 commented on tests/test_pascal_triangle.py
> +import os.path
и тут

2024-02-27 20:28 UTC, fortune76 requested changes
os.path надо убрать

2024-02-28 06:08 UTC, zv0r commented
Готово, босс

2024-02-28 06:59 UTC, merged